### ISSUE TITLE
FIFA18 is on Origin ？

### ISSUE THREAD

**Issue by wangzhangup** [ChintanTrivedi/DeepGamingAI_FIFARL#1]
On PC origin, I can't find shooting mode.

**Comment by ChintanTrivedi** [comment]
Yes, FIFA 18 is on origin. Once you get it from there, follow these steps shown here to get to the shooting mode:-

https://youtu.be/MasxAN-xZIU?t=1m38s

**Comment by wangzhangup** [comment]
@ChintanTrivedi  Is the fifa version "Standard edition"?
